### ISSUE TITLE
InvalidSkypeActionException: Not signed in

### ISSUE THREAD

**Issue by incrementing** [lin-e/Skype4Sharp#11]
Stacktrace: [pastebin](http://pastebin.com/raw/rQr2RB3N)
Program.cs: [pastebin](http://pastebin.com/raw/vS5jrCKK)

Error is thrown on line 26.
It happens on my main system as well as my VPS... so no... it's not my VPS's firewall. 
**Yes**, the skype login is **100%** correct.

plz fix sir or i cri

**Comment by incrementing** [comment]
nvm... my login was right... but meh account was banned #FuckMicrosoft

**Comment by ducc** [comment]
how did u manage that

**Comment by itsGhost** [comment]
> account gets banned for a legitimate reason
> justifies joining a hate train instead of justifying your actions

**Comment by incrementing** [comment]
I'd love to know that "legitimate reason". The account hadn't been used for months and then I go to login and it informs me "For your security, the Skype account linked to your Microsoft account has been suspended.".

**Comment by incrementing** [comment]
I feel like I should also point out this is still happening with a diffrent account.
![image](https://cloud.githubusercontent.com/assets/16342485/16895118/e5611694-4b62-11e6-9ef1-ff6ad1a2307e.png)

**Comment by lin-e** [comment]
A note:

```
skype.Login();
Console.WriteLine("[INFO]: Login complete, Starting event listeners...");
```

.Login() returns either true or false, depending on the login status (true => Success and vice versa), Pointing it out since your console indicates a successful login, and then the error is thrown when the login has failed and you attempt to start the poller.

I'm looking into it at the moment, the issue seems to be with getting the SkypeToken, since it's empty, and thus causes the lib to throw an exception trying to get a RegToken.

**Comment by itsGhost** [comment]
> I'd love to know that "legitimate reason". The account hadn't been used for months and then I go to login and it informs me "For your security, the Skype account linked to your Microsoft account has been suspended.".

fucking retard your account isnt banned
